CREATE TABLE TAR_ADDRESS (
    ID VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
    ADDRESS VARCHAR2(250),
    APTSUITE VARCHAR2(20) DEFAULT NULL,
    LONGITUDE FLOAT DEFAULT NULL,
    LATITUDE FLOAT DEFAULT NULL,
    CITY VARCHAR2(100) DEFAULT 'NY',
    COUNTRY VARCHAR2(100) DEFAULT 'USA',
    STATE VARCHAR2(100) DEFAULT 'Manhattan',
    ZIPCODE VARCHAR2(100) DEFAULT '10001',
    CREATED_BY VARCHAR2(36) NOT NULL,
    UPDATED_BY VARCHAR2(36) NOT NULL,
    DELETED_BY VARCHAR2(36) DEFAULT NULL
);

CREATE TABLE TAR_REGIONS (
 ID VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
 FIRST_NAME VARCHAR2(250),
 DESCRIPTION VARCHAR2(250), 
 CREATED_BY VARCHAR2(36) NOT NULL,
 UPDATED_BY VARCHAR2(36) NOT NULL,
 DELETED_BY VARCHAR2(36) DEFAULT NULL
);
 
 
 
 